### ISSUE TITLE
Non Dot Net Dll file in same folder, gives Error

### ISSUE THREAD

**Issue by shaileshbc** [Lifeng-Liang/DbEntry#14]
Dear Sir,
I am using Non Dot Net dll file in .net Application.
Due to this, it gives typeinitialisation error.
after digging into problem, found that problem occurs due to SearchAssemblies method in SimpleContainer.cs.
i changed the code a little bit and it started functioning.
'try
                        {
                            var assembly = Assembly.LoadFrom(fn);
                            assemblies.Add(assembly);
                        }
                        catch (Exception) { }'
let me know, if this is the correct way?
or any other solution on the same.
regards
Shailesh

**Comment by Lifeng-Liang** [comment]
at globle application start function, write: 

IocConfig.AddAssembly(typeof(IocConfig).Assembly);
IocConfig.AddAssembly(typeof(CK).Assembly);
IocConfig.AddAssembly(typeof(UrlBuilder).Assembly);

add your assembly which the models in by using AddAssembly function as well.

**Comment by ttcchh2008** [comment]
There is another way to solve it.

Just put the native dlls to another folder, eg. x86\,  and then pre load them into memory and hold them with a static List<IntPtr> .  
code snipt:
`/// <summary>
    /// 非托管程序集加载帮助类
    /// </summary>
    public class NativeDllHelper
    {
        private static readonly List<IntPtr> HInptrs = new List<IntPtr>();

        [DllImport("kernel32", BestFitMapping = false, CharSet = CharSet.Auto, SetLastError = true, ThrowOnUnmappableChar = true)]
        private static extern IntPtr LoadLibrary(string fileName);

        public static void PreLoadNativeDlls()
        {
            var dataLayers = (List<NativeDllInfo>)
                ConfigurationManager.GetSection("NativeDlls");

            dataLayers.Select(c => c.Path).ToList().ForEach(p =>
            {
                var fil = System.Environment.Is64BitProcess
                        ? @"x64\" + p : @"x86\" + p;

                if (File.Exists(fil))
                {
                    HInptrs.Add(LoadLibrary(fil));
                }
            });
        }
    }`
