### ISSUE TITLE
请问要怎么更新懒加载字段呢？

### ISSUE THREAD

**Issue by xjdata** [Lifeng-Liang/DbEntry#18]
因为历史原因，有表主键不是id的情况， 定义为 `IDbObject`。设置了某字段为`LazyLoad`

给该字段赋值时  `字段名.value=xxx`，会报 未将对象设置引用到对象实例 的错误。调试 该字段当时为null

请问要怎么更新懒加载字段呢？ 谢谢。

**Comment by Lifeng-Liang** [comment]
自己 new 一个 LazyLoad<Member> 的实例，在构造函数中赋值给该字段。
