### ISSUE TITLE
相对路径的配置

### ISSUE THREAD

**Issue by yonghuairuogu** [Lifeng-Liang/DbEntry#24]
我在使用mdb数据库，可以使用相对路径吗？或者在软件中利用字符串来配置连接。

**Comment by Lifeng-Liang** [comment]
[https://github.com/Lifeng-Liang/DbEntrySamples/blob/master/Orm/01/App.config](参见)

**Comment by yonghuairuogu** [comment]
如何在代码中利用字符串来配置连接呢？适用于通过文件选择框打开文件选择mdb的情况

**Comment by Lifeng-Liang** [comment]
目前不可以。
SqlQuerier使用了一种变通的方式，实际逻辑写在Console程序中，Form程序生成Console程序的config文件，并启动Console程序完成实际的工作。
